Milestone 5
pastorp3/Calculator pull request #4
Opened 2021-03-28 19:11 UTC by pastorp3

## Calculator Milestone 5: Event handlers
- Added event handler for buttons
- Implemented logic with event handler
- Added reactive display

2021-03-28 21:42 UTC, SmithVyne requested changes
### Changes Required 🤕 👍 
Hello, your project is nice. You just need to make a few additional improvements to get it approved. 

[REQUIRED] - Do not disable the Linters and improve your code quality.

2021-03-28 21:42 UTC, SmithVyne commented on src/components/App.js
> +/* eslint-disable no-unused-vars, class-methods-use-this,  react/destructuring-assignment */
You shouldn't be disabling these Lints. They are required to improve your code quality.

2021-03-28 21:42 UTC, SmithVyne commented on src/components/App.js
> +        <Display onInput={this.state.next ? this.state.next : this.state.total} />
Use object destructuring instead of using `this` repetitively.

2021-03-29 01:16 UTC, pastorp3 commented
- Added destructuring object to render

Note: Only disable no-unused-state on App.js because It shows a conflict with the operator in the state but I can not delete the operator from the state

2021-03-29 06:33 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @pastorp3, congratulations on fixing the comments outlined by the previous TSE :+1: Awesome :smile: The object destructuring used effectively, and also the linter disable reduced and explained :+1: I hereby approve the project

[Optional]
- Kindly improve the code commit messages going forward, kindly use `add` instead of `added`, `fix` instead of `fixed`, `import` instead of `imported`, `implement` instead of `implemented` etc
- It would be nice if we add a screenshot of the app
- Going forward, let us try to implement GitHub flow, for example; create a development branch from the master and also create the event branch from the development. So by this, we can merge to development but not master directly

Kindly go ahead and merge into development, if you really implemented the GitHub/git flow
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-03-29 16:04 UTC, merged